### ISSUE TITLE
AST without source location?

### ISSUE THREAD

**Issue by ngsankha** [lib-ruby-parser/lib-ruby-parser#10]
Thank you for your excellent work on this parser. I noticed the node structs have a range field `expression_l` to track the source text corresponding to the node. My use case is different -- I am generating Ruby program terms based on some specification (program synthesis), in such cases providing the range is a blocker. Can all the source location information be made optional? It would allow creation of an AST programmatically which can later be serialized to a Ruby program.

I totally understand if this is not a goal for the project.

**Comment by iliabylich** [comment]
Hello and sorry for delay

> Can all the source location information be made optional?

Technically - yes, practically - I think it's not worth it. Current type system is strong enough, and so users shouldn't check for `None` when it doesn't make sense (like in the case with `expression_l`, all AST nodes are based on some piece of source code).

I have a counter proposal. It looks like you only need node structs, but not the parser itself. If so you could use https://github.com/lib-ruby-parser/nodes to generate these nodes manually (but without location fields).

[Here's an example](https://github.com/lib-ruby-parser/lib-ruby-parser/blob/master/gen/nodes.rs) of how it's used in this repo. By the way, all other repos with bindings to other languages use it too.

**Comment by ngsankha** [comment]
Thanks! I agree, using the nodes repo would better. Closing this issue.
