### ISSUE TITLE
no method named `take_boxed_value` found for struct `PoolValue<Token>` in the current scope

### ISSUE THREAD

**Issue by perryqh** [lib-ruby-parser/lib-ruby-parser#102]
CI just started reporting this error today. I can't reproduce it locally.

> error[E0599]: no method named `take_boxed_value` found for struct `PoolValue<Token>` in the current scope
>      --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lib-ruby-parser-4.0.5+ruby-3.1.2/src/parser/parse.rs:15521:37
>       |
> 15521 |             let boxed_token = token.take_boxed_value();
>       |                                     ^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `take_value`

The [failing github action](https://github.com/alexevanczuk/packs/actions/runs/8510654264/job/23308691599?pr=178)

**Comment by iliabylich** [comment]
Oof, sorry, that's a new version of parser's dependency (that I think was pinned better than just `= MAJOR.MINOR` and so I didn't think about following SemVer). I've checked https://github.com/alexevanczuk/packs with master branch of `lib-ruby-parser`, it works fine so I'll cut a release soon.

**Comment by iliabylich** [comment]
I've released `v4.0.6` (`cargo test` on https://github.com/alexevanczuk/packs works for me locally). Node types have been extracted to `lib-ruby-parser-ast` crate, so compilation speed should be a bit better now (these types are still re-exported from `lib-ruby-parser`, so there are no breaking changes).

**Comment by perryqh** [comment]
Thanks @iliabylich!
