### ISSUE TITLE
Bazel build support?

### ISSUE THREAD

**Issue by jez** [lib-ruby-parser/lib-ruby-parser#15]
Thanks for all the work you've put into this project!

I'd love to try incorporating this into Sorbet. The biggest blocker is going to be getting lib-ruby-parser to build under the Bazel build system.

- Had you already planned to add Bazel build files for this project?
- If not, would you be open to me convincing you to either add them, or accept a pull request to add them?

We have some prior art of getting Rust dependencies to build under Bazel in Sorbet.

- [rubyfmt](https://github.com/penelopezone/rubyfmt) is a Ruby code formatter, implemented in Rust
- it builds using the [rules_rust] and [cargo-raze] projects
- here is [the PR integrating rubyfmt and sorbet](https://github.com/sorbet/sorbet/pull/3408)

Thanks again for this project, it looks very cool, and I'd love to be able to start trying it out in Sorbet.

[rules_rust]: https://github.com/bazelbuild/rules_rust
[cargo-raze]: https://github.com/google/cargo-raze

**Comment by iliabylich** [comment]
> Had you already planned to add Bazel build files for this project?

no

> If not, would you be open to me convincing you to either add them, or accept a pull request to add them?

Does it have to be a part of this repo? Also sorbet PR that you linked looks pretty big, are all of this changes required? I mean, it seems to be about running `cargo build`, no?

I've never used bazel, so I'm not the best person to work on it, but I'd be happy to review and merge PRs for that.

**Comment by jez** [comment]
> Does it have to be a part of this repo?

It does not. In the case of rubyfmt, the build config actually lives inside Sorbet.

> Also sorbet PR that you linked looks pretty big, are all of this changes required?

Nearly all of that PR is committing autogenerated code, which changes only when the cargo lockfile changes.

> I've never used bazel, so I'm not the best person to work on it, but I'd be happy to review and merge PRs for that.

Glad to hear. Would you also be open to introducing a CI step that tests that `master` builds under bazel?

The benefit to the bazel config living in this repo instead of in Sorbet's repo means that it changes whenever it needs to change (mostly: when deps change) and that anyone can use use the build files, instead of having to copy Sorbet's and potentially tweak them.

Thanks for the quick response!

**Comment by iliabylich** [comment]
> Would you also be open to introducing a CI step that tests that master builds under bazel?

Yes
