### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by seven1m** [lib-ruby-parser/lib-ruby-parser#3]
I'm writing a Ruby compiler in C++ and was very excited to run across this project today! Maybe I missed it, but it appears there is no license file?

Would you mind adding one so I can see if it's feasible to add this to my compiler? Thanks!

**Comment by iliabylich** [comment]
It's MIT (as mentioned in Cargo.toml - https://github.com/lib-ruby-parser/lib-ruby-parser/blob/master/Cargo.toml#L6), I'll add a license file later tomorrow once I have access to my laptop

**Comment by seven1m** [comment]
Oops, I just noticed the little "MIT" badge in the readme. That's great, and very generous! 

Still would be great to add the actual LICENSE file as is GitHub convention.

**Comment by iliabylich** [comment]
Done via web interface in https://github.com/lib-ruby-parser/lib-ruby-parser/commit/008af858635157f0a8a08adcacebbb0f2c79a30d
