### ISSUE TITLE
Following semantic versions rules

### ISSUE THREAD

**Issue by glebpom** [lib-ruby-parser/lib-ruby-parser#43]
Hi, and thanks for the great work. I'm wondering, if semantic versioning is something that are you consider? I'm constantly getting backward incompatibility when the crate gets updated with the patch version bump. I would suggest starting the 4.0.0-alpha* versions to work on interface changes. MongoDB crate used this approach successfully for several months, before releasing 2.0.0.

**Comment by iliabylich** [comment]
Hey,

> I'm wondering, if semantic versioning is something that are you consider?

No, this crate follows MRI versioning policy for simplicity.

> I'm constantly getting backward incompatibility when the crate gets updated with the patch version bump.

Are you referring to this crate or to `MongoDB` here?

**Comment by glebpom** [comment]
I'm referring MongoDB as an example where the approach with a prerelease version worked well.  

The compilation breaks for me when the patch version of  `lib-ruby-parser` gets updated.

I'd suggest pointing in the README that this package doesn't follow the semantic versioning, because it opposes the [cargo rules](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field) which typical rust developer gets used to. So instead of `lib-ruby-parser = "3.0.9"` in `Cargo.toml` one should actually fixate the exact version (`lib-ruby-parser = "=3.0.9"`) and don't rely on `cargo update` with the package.

**Comment by iliabylich** [comment]
> one should actually fixate the exact version (lib-ruby-parser = "=3.0.9") and don't rely on cargo update with the package

That's a good point, thanks, I'll add it to README.

The reason why semver doesn't really work is that Ruby itself changes way too frequently. New API can be added in patch version update but for `lib-ruby-parser` that'd be a major version bump. I'm not implying that it happens every day, but it happened multiple times in the past. If `parser` gem would follow semver it'd outride Chrome version a long time ago 😄 

I'm closing it with a note to myself to mention versioning in readme. Feel free to reopen if there's still something you'd like to discuss about it.

**Comment by iliabylich** [comment]
> The compilation breaks for me when the patch version of lib-ruby-parser gets updated.

by the way, do you remember what exactly did break for you? I didn't change anything except for `ParserOptions::debug` field that isn't supposed to be used for anything but development.

**Comment by glebpom** [comment]
> The reason why semver doesn't really work is that Ruby itself changes way too frequently. New API can be added in patch version update but for lib-ruby-parser that'd be a major version bump. I'm not implying that it happens every day, but it happened multiple times in the past. If parser gem would follow semver it'd outride Chrome version a long time ago 😄

You may also check how [zstd versioning](https://crates.io/crates/zstd) is implemented. They add core library version as a metadata to version name, while bumping the main version according to semver rules. 

> by the way, do you remember what exactly did break for you? I didn't change anything except for ParserOptions::debug field that isn't supposed to be used for anything but development.

Yes, the last upgrade removed the `debug` field from `ParserOptions`.  If it's a `pub` field it could be used, just like happened in my case.
Before that, the String representation has changed in Node. I think `bytes` was removed in favor of `raw`.

**Comment by iliabylich** [comment]
Thanks for pointing to zstd, I actually think I'll switch to similar pattern.

> Before that, the String representation has changed in Node. I think bytes was removed in favor of raw.

yes, I think I didn't even think about this change when I made it. sorry, I'll think twice next time. I experiment a lot in this repo to get better performance, and changes like those should bump major version.

**Comment by glebpom** [comment]
You are doing a great job with this repo; please keep going! A bit more stability would make your work even more fantastic.
