### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by pirj** [lib-ruby-parser/lib-ruby-parser#52]
Any chance for Ruby bindings?
I would volunteer, but have no prior experience in writing bindings for Rust code, or any FFI for a Ruby gem in general.

Is there an interest? `rubocop` (and `rubocop-ast`) and `graphql` gems depend on `parser`. If there was a more performant drop-in replacement, time and processing power could be saved.

**Comment by iliabylich** [comment]
Hello.

Yes, there's a [repo for that](https://github.com/lib-ruby-parser/ruby-bindings) that I'm updating literally right now 😄 .

It'll be based on [c bindings](https://github.com/lib-ruby-parser/c-bindings) that I finished updating several day ago, so no knowledge of Rust is required.

Unfortunately during last ~6 months I was busy with other ideas around `lib-ruby-parser` and I simply had no time to finish Ruby bindings. I hope it will be ready in several days, however making it memory leak/corruption-safe will take some time.

It's actually funny that I started working on Ruby bindings a day before `lib-ruby-parser` was linked in Ruby Weekly.

**Comment by pirj** [comment]
>  actually funny that I started working on Ruby bindings a day before lib-ruby-parser was linked in Ruby Weekly.

Stars aligned 🌟 🌟 

I'll close this ticket and will watch the repo closely. Thanks for creating `lib-ruby-parser`!

**Comment by iliabylich** [comment]
@pirj I've released `lib-ruby-parser` beta3 version that supports 2.6.x/2.7.x/3.0.x on Linux/Mac/Windows and ships as a native gem.

```
gem install lib-ruby-parser --pre
```

should install it, no local compilation is required. It's still beta because I'm not sure about the API I've got, so things can change in the near future.

**Comment by pirj** [comment]
There's a minor hiccup that healed itself:
```
$ gem install lib-ruby-parser --pre
Fetching lib-ruby-parser-0.0.1.beta3-x86_64-darwin.gem
Successfully installed lib-ruby-parser-0.0.1.beta3-x86_64-darwin
Installing YARD documentation for lib-ruby-parser-0.0.1.beta3-x86_64-darwin...
[error]: Exception occurred while generating 'LibRubyParser/Messages/EncodingError.html'
[error]: ArgumentError: unknown encoding name: foo
[error]: Stack trace:
        (tokenize):1
        /Users/pirj/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/yard-0.9.26/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
        /Users/pirj/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/yard-0.9.26/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
        /Users/pirj/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/yard-0.9.26/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
        /Users/pirj/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/yard-0.9.26/lib/yard/parser/base.rb:19:in `parse'
        /Users/pirj/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/yard-0.9.26/lib/yard/parser/ruby/token_resolver.rb:17:in `initialize'

Done installing documentation for lib-ruby-parser after 8 seconds
1 gem installed
$ gem install --verbose lib-ruby-parser --pre
HEAD https://rubygems.org/api/v1/dependencies
200 OK
GET https://rubygems.org/api/v1/dependencies?gems=lib-ruby-parser
200 OK
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/README.md
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/lib-ruby-parser.gemspec
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/lib/lib-ruby-parser.rb
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/lib/lib-ruby-parser/messages.rb
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/lib/lib-ruby-parser/native/lib_ruby_parser.bundle
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/lib/lib-ruby-parser/nodes.rb
/Users/pirj/.rvm/gems/ruby-2.7.2@rubocop/gems/lib-ruby-parser-0.0.1.beta3-x86_64-darwin/lib/lib-ruby-parser/version.rb
Successfully installed lib-ruby-parser-0.0.1.beta3-x86_64-darwin
Done installing documentation for lib-ruby-parser after 0 seconds
1 gem installed
```

**Comment by iliabylich** [comment]
🤦  YARD tries to parse comments that I attached to diagnostic messages (i.e. warnings/errors), of course some attached examples produce errors if you parse them - that's why I added those comments, to explain how get these errors - but I didn't expect that it can break installation.

Thanks for letting me know, I have `--no-ri --no-rdoc` set globally and I didn't even know about it.
