### ISSUE TITLE
Support for pattern matching

### ISSUE THREAD

**Issue by alexevanczuk** [lib-ruby-parser/lib-ruby-parser#85]
Hello!

I'd love to support parsing pattern matching in Ruby 3.2:
https://docs.ruby-lang.org/en/3.2/syntax/pattern_matching_rdoc.html

Right now when I encounter pattern matching syntax I receive this panic message: `expected variables_stack to have at least 1 layer`

Would it be possible to add support for this syntax?

I started looking into adding it myself but I'm having trouble building this project with `cargo build`. 

```
~/workspace/lib-ruby-parser - (master) $ rustup default nightly-2022-07-24 
info: using existing install for 'nightly-2022-07-24-aarch64-apple-darwin'
info: default toolchain set to 'nightly-2022-07-24-aarch64-apple-darwin'

  nightly-2022-07-24-aarch64-apple-darwin unchanged - rustc 1.64.0-nightly (93ffde6f0 2022-07-23)

~/workspace/lib-ruby-parser - (master) $ cargo build
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/alex.evanczuk/workspace/lib-ruby-parser/lib-ruby-parser/Cargo.toml
workspace: /Users/alex.evanczuk/workspace/lib-ruby-parser/Cargo.toml
   Compiling lib-ruby-parser v4.0.4+ruby-3.1.1 (/Users/alex.evanczuk/workspace/lib-ruby-parser/lib-ruby-parser)
   Compiling rustix v0.36.10
   Compiling serde_json v1.0.94
   Compiling toml v0.5.11
   Compiling backtrace v0.3.67
   Compiling findshlibs v0.10.2
error[E0583]: file not found for module `parse`
 --> lib-ruby-parser/src/parser/mod.rs:1:1
  |
1 | mod parse;
  | ^^^^^^^^^^
  |
  = help: to create the module `parse`, create file "lib-ruby-parser/src/parser/parse.rs" or "lib-ruby-parser/src/parser/parse/mod.rs"

error[E0583]: file not found for module `message_enum`
 --> lib-ruby-parser/src/error/messages/mod.rs:1:1
  |
1 | mod message_enum;
  | ^^^^^^^^^^^^^^^^^
  |
  = help: to create the module `message_enum`, create file "lib-ruby-parser/src/error/messages/message_enum.rs" or "lib-ruby-parser/src/error/messages/message_enum/mod.rs"
```

Any tips on building this project? I was hoping I could at least start with a failing test for the new syntax!

**Comment by iliabylich** [comment]
Hello.

Yes, 3.2 syntax is not supported. Not because it's impossible, I just don't have time right now.

> Any tips on building this project? I was hoping I could at least start with a failing test for the new syntax!

You can check how CI builds it [here](https://github.com/lib-ruby-parser/lib-ruby-parser/blob/master/.github/workflows/test-rust.yml#L25-L58), you need to:

1. `git clone` with submodules
2. have `ragel` and `bison` installed locally
3. run `make codegen-tests` to import tests from `whitequark/parser` submodule
4. run `make codegen-rust` to generate all the Nodes and diagnostic Messages (based on https://github.com/lib-ruby-parser/nodes). IIRC it also generates the parser (`.y` -> `.rs`), most of the codegen functionality of this crate is hidden behind features, for local development I think only `lib-ruby-parser/codegen-y` and `lib-ruby-parser/codegen-rust` are required. Additionally there's `lib-ruby-parser/debug-all` feature that enabled printing of messy debug output.

**Comment by iliabylich** [comment]
You have a really old version of `bison`, make sure to install at least `3.7.3` (mine is `3.8.2`). I think both homebrew and apt repos have it.

**Comment by alexevanczuk** [comment]
Thanks – turns out I was using a version installed by `Xcode`.

Now I'm seeing this:
```
~/workspace/lib-ruby-parser - (master) $ bison --version
bison (GNU Bison) 3.8.2
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
~/workspace/lib-ruby-parser - (master) $ ragel --version
Ragel State Machine Compiler version 6.10 March 2017
Copyright (c) 2001-2009 by Adrian Thurston
~/workspace/lib-ruby-parser - (master) $ rustc --version
rustc 1.64.0-nightly (93ffde6f0 2022-07-23)
~/workspace/lib-ruby-parser - (master) $ cargo test
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/alex.evanczuk/workspace/lib-ruby-parser/lib-ruby-parser/Cargo.toml
workspace: /Users/alex.evanczuk/workspace/lib-ruby-parser/Cargo.toml
   Compiling inferno v0.11.15
error[E0106]: missing lifetime specifier
  --> /Users/alex.evanczuk/.cargo/registry/src/github.com-1ecc6299db9ec823/inferno-0.11.15/src/flamegraph/color/mod.rs:83:25
   |
83 |     pub const VARIANTS: &[&'static str] = &[
   |                         ^ expected named lifetime parameter
   |
help: consider using the `'static` lifetime
   |
83 |     pub const VARIANTS: &'static [&'static str] = &[
   |                          +++++++
help: consider introducing a named lifetime parameter
   |
81 ~ impl<'a> Palette {
82 |     /// The valid set of palettes (via `FromStr`).
83 ~     pub const VARIANTS: &'a [&'static str] = &[
   |

For more information about this error, try `rustc --explain E0106`.
error: could not compile `inferno` due to previous error
```

**Comment by iliabylich** [comment]
Not sure what's missing, the error comes not from us but from `inferno` which is (as I remember) a transient dependency of `pprof` which is a crate for profiling. Maybe try switching to stable Rust? Also I'm not even compiling it when running tests (I've just double-checked it locally). Could you try running just `make test` please? It's just a wrapper around `cargo test` with a few more custom options (that I think are irrelevant, but still)

**Comment by alexevanczuk** [comment]
Okay – not sure what I changed, but it looks like my tests are all running and passing now!

Let me know if you have any high-level steps to add failing tests for the new syntax and where and how I might consider adding support for this. If not, I can try poking around for a bit.

Just for some context – I've been using this in a side-project I'm working on, a [reimplementation of packwerk in Rust](https://github.com/alexevanczuk/packs). Wanted to thank you for building this great library!

**Comment by iliabylich** [comment]
> Let me know if you have any high-level steps to add failing tests for the new syntax and where and how I might consider adding support for this. If not, I can try poking around for a bit.

It's never easy. The best solution I could come up is syncing tests from `whitequark/parser` repo which is probably the most fully covered ruby parser in terms of testing. As you can see this submodule points to one of the latest `3.1` revisions and there's a script that "replays" its tests and records input/output/locations/errors etc.

So my standard algorithm for updating is:

1. bump `parser` submodule a few revisions ahead
2. re-generate tests
3. fix what's missing by looking at the diff of MRI/parser gem
4. backporting it
5. commit & push
6. goto 1 until there's nothing to backport.

Could you share the code that makes it panic please? I'm not even sure if it's a new syntax or just a bug.

If it's a bug the fix hopefully should be simple, add a new file in `tests/fixtures` directory (depending on the type of the test in either `lexer` or `parser` subdirectory, you probably need a tests for the parser), include it in the corresponding `tests/src/<test type>/manual.rs` and make it pass.

**Comment by alexevanczuk** [comment]
> Could you share the code that makes it panic please? I'm not even sure if it's a new syntax or just a bug.
Yep! Sorry for the delay on this. This was a bug reported for my library but I'm still working to get a minimal reproduction of the issue from the user. I'll let you know when I have that! I haven't been able to reproduce the issue when using `lib-ruby-parser` to test various examples of pattern matching from several documentation sources I found so it's possible this is a false alarm 🙏🏼 

Thanks for the information on building the project, adding tests, etc.!!

**Comment by alexevanczuk** [comment]
@iliabylich Got an update! Here's the code that causes a panic:

```ruby
config = { a: { b: :c } }
config => a: {b:}
```

Parsing that gives me:
```
thread 'main' panicked at 'expected variables_stack to have at least 1 layer', /Users/alex.evanczuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lib-ruby-parser-4.0.4+ruby-3.1.1/src/variables_stack.rs:41:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Let me know if you think this is just a bug or would be considered new syntax!

**Comment by iliabylich** [comment]
Yes, that's a bug inherited from `whitequark/parser` (https://github.com/whitequark/parser/commit/27f83bab58d4f44dba7e20f7b46920044e0a2365, literally the first non-backported commit in the queue), I've fixed it in https://github.com/lib-ruby-parser/lib-ruby-parser/commit/c4910e3db963a59831ef195f43f4e6cf927039a0.

Do you need a release?

**Comment by alexevanczuk** [comment]
Oh amazing! A release would be great whenever you get a chance. Thanks so much!
