### ISSUE TITLE
Named capture assignment

### ISSUE THREAD

**Issue by kddnewton** [lib-ruby-parser/lib-ruby-parser#90]
Hi Ilya! 👋 

It appears that this library doesn't expose nodes that assign local variables through named capture groups:

```ruby
/(?<match>bar)/ =~ 'bar'; match
```

that `match` should be an lvar, but right now it's a send.

**Comment by iliabylich** [comment]
Hello!

This should work, but it requires `onig` feature to be enabled - https://github.com/lib-ruby-parser/lib-ruby-parser/blob/master/src/builder.rs#L2372-L2376, it's documented [in the README](https://github.com/lib-ruby-parser/lib-ruby-parser#regexes)

**Comment by kddnewton** [comment]
Ahh I'm so sorry! You're totally right. It works as expected!
